<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Done</name>
   <tag></tag>
   <elementGuidId>0e323b97-5d44-4387-a2c8-f183e135e2f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div[2]/div[5]/div[2]/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sc-12foipm-64.jkgFUQ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Done&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d8703ee-bc17-4d23-a9a8-0ca3b3e1731e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-12foipm-64 jkgFUQ</value>
      <webElementGuid>b2f54cc6-960a-4bf7-af61-29295bdbdf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>e17c269c-4b8c-4bf5-969c-57c80929f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 bPZJjI&quot;]/div[@class=&quot;sc-1gt8xf5-3 helaNf&quot;]/div[@class=&quot;sc-12foipm-16 wfIEw&quot;]/div[@class=&quot;sc-12foipm-0 iiZOql&quot;]/div[@class=&quot;sc-12foipm-20 cOYHtZ&quot;]/div[@class=&quot;sc-12foipm-53 hQpljf&quot;]/div[@class=&quot;sc-12foipm-62 cHjaTW&quot;]/a[@class=&quot;sc-12foipm-64 jkgFUQ&quot;]</value>
      <webElementGuid>42604ce2-5214-4adf-be72-501d274cc9fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div[2]/div[5]/div[2]/div[3]/a[2]</value>
      <webElementGuid>46e46e1e-c50a-4f87-a3c8-d3dc6c626e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Done')]</value>
      <webElementGuid>dcb0acff-40e8-4a58-b681-2e5f61ad4c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::a[1]</value>
      <webElementGuid>30b3c431-c819-4f52-bb7c-cb072f066bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='first class'])[1]/following::a[2]</value>
      <webElementGuid>cab8fd42-d823-4910-b5ea-def394e890d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Benefits'])[1]/preceding::a[1]</value>
      <webElementGuid>5fba7ffc-436a-49fd-ad6e-2019a6366f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Fares'])[1]/preceding::a[1]</value>
      <webElementGuid>7d02ba5f-e6e8-49e2-ba2d-c53d34f34ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>6a5c45d7-658e-4959-85e6-a3e19f7fd0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>6d2a7df0-90f4-4e9e-ad68-a84ff35a5a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>a8e45561-d4e6-47d7-9801-50ed4d773b48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
