<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Travellers  Class_sc-12foipm-8 eXKWBG _f0a772</name>
   <tag></tag>
   <elementGuidId>48e4cf0e-deb6-4890-a7b2-9bd5e42c727c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div[2]/div[5]/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-12foipm-8.eXKWBG.fswDownArrow.fswDownArrowTraveller</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p >> internal:has-text=&quot;1 Adult&quot;i >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b37974d4-9f58-4eb7-9fd2-9395613842ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-12foipm-8 eXKWBG fswDownArrow fswDownArrowTraveller</value>
      <webElementGuid>28160eb4-aebf-4cbf-b501-1fe15f2745e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 bPZJjI&quot;]/div[@class=&quot;sc-1gt8xf5-3 helaNf&quot;]/div[@class=&quot;sc-12foipm-16 wfIEw&quot;]/div[@class=&quot;sc-12foipm-0 iiZOql&quot;]/div[@class=&quot;sc-12foipm-20 cOYHtZ&quot;]/div[@class=&quot;sc-12foipm-2 eTBlJr fswFld&quot;]/p[@class=&quot;sc-12foipm-4 czGBLf fswWidgetTitle&quot;]/span[@class=&quot;sc-12foipm-8 eXKWBG fswDownArrow fswDownArrowTraveller&quot;]</value>
      <webElementGuid>0cbec55b-2b1a-4f45-933d-8ebdf250ae2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div[2]/div[5]/div/p/span</value>
      <webElementGuid>4acb2916-bd4a-466a-824b-bafa9e61fe09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/p/span</value>
      <webElementGuid>52aae9d7-a241-4ad2-be88-3ae8e05dedde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
