<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>f2dd8701-f90e-47f3-a344-1538ea0eb8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Travellers &amp; Class'])[2]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^1$/ >> internal:role=img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b09e518e-1f7f-4c15-baa1-6a92c7c7cf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>76bf2f92-d17d-4919-a634-6bc25fdbfd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>68f2ce05-5249-4473-a6dc-5198e4800f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>17777a66-4eaf-41e4-8f3a-5ecaf1f3fd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>58eb3b19-f87f-43db-8a1d-184ba4007bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 bPZJjI&quot;]/div[@class=&quot;sc-1gt8xf5-3 helaNf&quot;]/div[@class=&quot;sc-12foipm-16 wfIEw&quot;]/div[@class=&quot;sc-12foipm-0 iiZOql&quot;]/div[@class=&quot;sc-12foipm-20 cOYHtZ&quot;]/div[@class=&quot;sc-12foipm-53 hQpljf&quot;]/div[@class=&quot;sc-12foipm-60 ejCqNo&quot;]/div[@class=&quot;sc-12foipm-61 kiJTGn&quot;]/div[@class=&quot;sc-12foipm-65 hkLaIV&quot;]/div[@class=&quot;sc-12foipm-47 pZQPB&quot;]/div[@class=&quot;sc-12foipm-50 gaoQkJ&quot;]/span[@class=&quot;sc-12foipm-51 kZvHQU&quot;]/svg[1]</value>
      <webElementGuid>c01f4969-4e0e-4c06-aa0d-59b2b4a54490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travellers &amp; Class'])[2]/following::*[name()='svg'][2]</value>
      <webElementGuid>e07afc3f-0724-4951-8381-9733b7d8e4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travellers &amp; Class'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>d6bce0c6-cad4-4e66-930a-2459e2dda5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='economy'])[3]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>9de90efa-e1eb-45f8-88d4-f8e0e3d00a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='premium economy'])[1]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>a5da4904-006a-43ab-be69-ec3bc9902163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
